# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import aprilcam_pb2 as aprilcam__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in aprilcam_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AprilCamStub(object):
    """---------------------------------------------------------------------------
    AprilCam gRPC service
    ---------------------------------------------------------------------------

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListCameras = channel.unary_unary(
                '/aprilcam.AprilCam/ListCameras',
                request_serializer=aprilcam__pb2.Empty.SerializeToString,
                response_deserializer=aprilcam__pb2.ListCamerasResponse.FromString,
                _registered_method=True)
        self.EnumerateCameras = channel.unary_unary(
                '/aprilcam.AprilCam/EnumerateCameras',
                request_serializer=aprilcam__pb2.Empty.SerializeToString,
                response_deserializer=aprilcam__pb2.EnumerateCamerasResponse.FromString,
                _registered_method=True)
        self.OpenCamera = channel.unary_unary(
                '/aprilcam.AprilCam/OpenCamera',
                request_serializer=aprilcam__pb2.OpenCameraRequest.SerializeToString,
                response_deserializer=aprilcam__pb2.OpenCameraResponse.FromString,
                _registered_method=True)
        self.CloseCamera = channel.unary_unary(
                '/aprilcam.AprilCam/CloseCamera',
                request_serializer=aprilcam__pb2.CameraRequest.SerializeToString,
                response_deserializer=aprilcam__pb2.Empty.FromString,
                _registered_method=True)
        self.ReloadCalibration = channel.unary_unary(
                '/aprilcam.AprilCam/ReloadCalibration',
                request_serializer=aprilcam__pb2.CameraRequest.SerializeToString,
                response_deserializer=aprilcam__pb2.Empty.FromString,
                _registered_method=True)
        self.Shutdown = channel.unary_unary(
                '/aprilcam.AprilCam/Shutdown',
                request_serializer=aprilcam__pb2.Empty.SerializeToString,
                response_deserializer=aprilcam__pb2.Empty.FromString,
                _registered_method=True)
        self.GetCameraInfo = channel.unary_unary(
                '/aprilcam.AprilCam/GetCameraInfo',
                request_serializer=aprilcam__pb2.CameraRequest.SerializeToString,
                response_deserializer=aprilcam__pb2.CameraInfoResponse.FromString,
                _registered_method=True)
        self.CaptureFrame = channel.unary_unary(
                '/aprilcam.AprilCam/CaptureFrame',
                request_serializer=aprilcam__pb2.CameraRequest.SerializeToString,
                response_deserializer=aprilcam__pb2.CaptureFrameResponse.FromString,
                _registered_method=True)
        self.GetTags = channel.unary_unary(
                '/aprilcam.AprilCam/GetTags',
                request_serializer=aprilcam__pb2.CameraRequest.SerializeToString,
                response_deserializer=aprilcam__pb2.TagFrameResponse.FromString,
                _registered_method=True)
        self.WhereIs = channel.unary_unary(
                '/aprilcam.AprilCam/WhereIs',
                request_serializer=aprilcam__pb2.WhereRequest.SerializeToString,
                response_deserializer=aprilcam__pb2.WhereResponse.FromString,
                _registered_method=True)
        self.GetImageStream = channel.unary_unary(
                '/aprilcam.AprilCam/GetImageStream',
                request_serializer=aprilcam__pb2.StreamRequest.SerializeToString,
                response_deserializer=aprilcam__pb2.StreamEndpoint.FromString,
                _registered_method=True)
        self.GetTagStream = channel.unary_unary(
                '/aprilcam.AprilCam/GetTagStream',
                request_serializer=aprilcam__pb2.StreamRequest.SerializeToString,
                response_deserializer=aprilcam__pb2.StreamEndpoint.FromString,
                _registered_method=True)
        self.PublishOverlay = channel.unary_unary(
                '/aprilcam.AprilCam/PublishOverlay',
                request_serializer=aprilcam__pb2.PublishOverlayRequest.SerializeToString,
                response_deserializer=aprilcam__pb2.StatusReply.FromString,
                _registered_method=True)


class AprilCamServicer(object):
    """---------------------------------------------------------------------------
    AprilCam gRPC service
    ---------------------------------------------------------------------------

    """

    def ListCameras(self, request, context):
        """Camera lifecycle
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EnumerateCameras(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def OpenCamera(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CloseCamera(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReloadCalibration(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Shutdown(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCameraInfo(self, request, context):
        """One-shot queries (no streaming required)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CaptureFrame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTags(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WhereIs(self, request, context):
        """Natural-language playfield feature lookup ("where is the blue dot")
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetImageStream(self, request, context):
        """Stream discovery — allocates a socket/port pair on demand
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTagStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PublishOverlay(self, request, context):
        """Live overlay injection — push overlay elements to all tag stream subscribers
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AprilCamServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListCameras': grpc.unary_unary_rpc_method_handler(
                    servicer.ListCameras,
                    request_deserializer=aprilcam__pb2.Empty.FromString,
                    response_serializer=aprilcam__pb2.ListCamerasResponse.SerializeToString,
            ),
            'EnumerateCameras': grpc.unary_unary_rpc_method_handler(
                    servicer.EnumerateCameras,
                    request_deserializer=aprilcam__pb2.Empty.FromString,
                    response_serializer=aprilcam__pb2.EnumerateCamerasResponse.SerializeToString,
            ),
            'OpenCamera': grpc.unary_unary_rpc_method_handler(
                    servicer.OpenCamera,
                    request_deserializer=aprilcam__pb2.OpenCameraRequest.FromString,
                    response_serializer=aprilcam__pb2.OpenCameraResponse.SerializeToString,
            ),
            'CloseCamera': grpc.unary_unary_rpc_method_handler(
                    servicer.CloseCamera,
                    request_deserializer=aprilcam__pb2.CameraRequest.FromString,
                    response_serializer=aprilcam__pb2.Empty.SerializeToString,
            ),
            'ReloadCalibration': grpc.unary_unary_rpc_method_handler(
                    servicer.ReloadCalibration,
                    request_deserializer=aprilcam__pb2.CameraRequest.FromString,
                    response_serializer=aprilcam__pb2.Empty.SerializeToString,
            ),
            'Shutdown': grpc.unary_unary_rpc_method_handler(
                    servicer.Shutdown,
                    request_deserializer=aprilcam__pb2.Empty.FromString,
                    response_serializer=aprilcam__pb2.Empty.SerializeToString,
            ),
            'GetCameraInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCameraInfo,
                    request_deserializer=aprilcam__pb2.CameraRequest.FromString,
                    response_serializer=aprilcam__pb2.CameraInfoResponse.SerializeToString,
            ),
            'CaptureFrame': grpc.unary_unary_rpc_method_handler(
                    servicer.CaptureFrame,
                    request_deserializer=aprilcam__pb2.CameraRequest.FromString,
                    response_serializer=aprilcam__pb2.CaptureFrameResponse.SerializeToString,
            ),
            'GetTags': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTags,
                    request_deserializer=aprilcam__pb2.CameraRequest.FromString,
                    response_serializer=aprilcam__pb2.TagFrameResponse.SerializeToString,
            ),
            'WhereIs': grpc.unary_unary_rpc_method_handler(
                    servicer.WhereIs,
                    request_deserializer=aprilcam__pb2.WhereRequest.FromString,
                    response_serializer=aprilcam__pb2.WhereResponse.SerializeToString,
            ),
            'GetImageStream': grpc.unary_unary_rpc_method_handler(
                    servicer.GetImageStream,
                    request_deserializer=aprilcam__pb2.StreamRequest.FromString,
                    response_serializer=aprilcam__pb2.StreamEndpoint.SerializeToString,
            ),
            'GetTagStream': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTagStream,
                    request_deserializer=aprilcam__pb2.StreamRequest.FromString,
                    response_serializer=aprilcam__pb2.StreamEndpoint.SerializeToString,
            ),
            'PublishOverlay': grpc.unary_unary_rpc_method_handler(
                    servicer.PublishOverlay,
                    request_deserializer=aprilcam__pb2.PublishOverlayRequest.FromString,
                    response_serializer=aprilcam__pb2.StatusReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aprilcam.AprilCam', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aprilcam.AprilCam', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AprilCam(object):
    """---------------------------------------------------------------------------
    AprilCam gRPC service
    ---------------------------------------------------------------------------

    """

    @staticmethod
    def ListCameras(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aprilcam.AprilCam/ListCameras',
            aprilcam__pb2.Empty.SerializeToString,
            aprilcam__pb2.ListCamerasResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def EnumerateCameras(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aprilcam.AprilCam/EnumerateCameras',
            aprilcam__pb2.Empty.SerializeToString,
            aprilcam__pb2.EnumerateCamerasResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def OpenCamera(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aprilcam.AprilCam/OpenCamera',
            aprilcam__pb2.OpenCameraRequest.SerializeToString,
            aprilcam__pb2.OpenCameraResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CloseCamera(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aprilcam.AprilCam/CloseCamera',
            aprilcam__pb2.CameraRequest.SerializeToString,
            aprilcam__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReloadCalibration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aprilcam.AprilCam/ReloadCalibration',
            aprilcam__pb2.CameraRequest.SerializeToString,
            aprilcam__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Shutdown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aprilcam.AprilCam/Shutdown',
            aprilcam__pb2.Empty.SerializeToString,
            aprilcam__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCameraInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aprilcam.AprilCam/GetCameraInfo',
            aprilcam__pb2.CameraRequest.SerializeToString,
            aprilcam__pb2.CameraInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CaptureFrame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aprilcam.AprilCam/CaptureFrame',
            aprilcam__pb2.CameraRequest.SerializeToString,
            aprilcam__pb2.CaptureFrameResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTags(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aprilcam.AprilCam/GetTags',
            aprilcam__pb2.CameraRequest.SerializeToString,
            aprilcam__pb2.TagFrameResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WhereIs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aprilcam.AprilCam/WhereIs',
            aprilcam__pb2.WhereRequest.SerializeToString,
            aprilcam__pb2.WhereResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetImageStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aprilcam.AprilCam/GetImageStream',
            aprilcam__pb2.StreamRequest.SerializeToString,
            aprilcam__pb2.StreamEndpoint.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTagStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aprilcam.AprilCam/GetTagStream',
            aprilcam__pb2.StreamRequest.SerializeToString,
            aprilcam__pb2.StreamEndpoint.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PublishOverlay(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aprilcam.AprilCam/PublishOverlay',
            aprilcam__pb2.PublishOverlayRequest.SerializeToString,
            aprilcam__pb2.StatusReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
